[package]
name = "attendance_management"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0"
thiserror = "1.0"
cgi = "0.6"
serde = { version="1.0.160", features=["derive"] }
serde_json = "1.0.96"
chrono = "0.4.24"
chrono-tz = "0.8.2"
